// Generated with Typst 0.15.1. Keep the fixed metadata date and compile
// timestamp in the justfile recipe so the PDF remains byte-reproducible.
#set document(
  title: [page PDF/A-1b conformance fixture],
  author: "page test suite",
  description: [A deterministic PDF/A-1b integration fixture for page and veraPDF.],
  keywords: ("PDF/A-1b", "veraPDF", "Typst"),
  date: datetime(year: 2026, month: 1, day: 1),
)
#set page(paper: "a4", margin: 25mm)
#set text(font: "Libertinus Serif", lang: "en", size: 10pt)
#set heading(numbering: "1.")

#title()

This document is generated by Typst as a deterministic, standards-targeted
fixture. It exercises embedded text, document metadata, vector graphics, and
colour-managed output.

== Content

- Embedded Libertinus Serif text
- A PDF/A-1b identification declaration
- Matching document information and XMP metadata
- An RGB output intent supplied by Typst

#rect(
  width: 100%,
  height: 18mm,
  fill: rgb("#d9e8f5"),
  stroke: 0.8pt + rgb("#285f8f"),
  radius: 2pt,
)

#table(
  columns: (1fr, 2fr),
  inset: 5pt,
  stroke: 0.5pt + rgb("#285f8f"),
  table.header([Property], [Expected value]),
  [PDF version], [1.4],
  [Conformance], [PDF/A-1b],
  [Reference validator], [veraPDF 1.30.2],
)
