[project]
site_name = "page"
repo_url = "https://github.com/pagestandards/page"
site_url = "https://pagestandards.github.io/page/"
site_description = "Experimental veraPDF-compliant PDF/A validation, written in Rust"
site_author = "Joseph Barbier"
extra_css = ["stylesheets/style.css"]
nav = [
  { "Home" = "index.md" },
  { "Usage" = [
    "api/cli.md",
    "api/rust.md",
    "api/python.md",
    "api/nodejs.md",
  ] },
  { "Rule Reference" = ["rules/pdfa-1b-rule-mapping.md"] },
  { "FAQ" = ["faq.md"] }
]

[project.theme]
language = "en"
features = [
  "announce.dismiss",
  "content.code.annotate",
  "content.code.copy",
  "content.footnote.tooltips",
  "content.tooltips",
  "navigation.footer",
  "navigation.indexes",
  "navigation.instant",
  "navigation.instant.prefetch",
  "navigation.path",
  "navigation.tabs",
  "navigation.sections",
  "navigation.top",
  "navigation.tracking",
  "search.highlight",
  "navigation.prune",
]

[[project.theme.palette]]
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Dark mode"

[[project.theme.palette]]
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Light mode"

[project.theme.icon]
repo = "fontawesome/brands/github"
