[project]
site_name = "page"
repo_url = "https://github.com/josephbarbierdarnal/page"
site_url = "https://josephbarbierdarnal.github.io/page/"
site_description = "PDF/A and PDF/UA validation engine, written in Rust"
site_author = "Joseph Barbier"
extra_css = ["stylesheets/style.css"]
nav = [
  { "Home" = "index.md" },
  { "Installation" = "installation.md" },
  { "Usage" = [
    { "CLI" = ["api/cli/quick-start.md"] },
    { "Rust" = ["api/rust/quick-start.md", "api/rust/safety-limits.md", "api/rust/faillures.md"] },
  ] },
  { "Reference" = [
    "rules/pdfa-1-rule-mapping.md",
    "rules/pdfa-2-3-rule-mapping.md",
    "rules/pdfua-1-rule-mapping.md",
  ] },
  { "About" = ["about/faq.md", "about/pdf-format.md"] },
]

[project.theme]
logo = "images/logo-on-light.svg"
language = "en"
custom_dir = "docs/overrides"
features = [
  "announce.dismiss",
  "content.code.annotate",
  "content.code.copy",
  "content.footnote.tooltips",
  "content.tooltips",
  "navigation.footer",
  "navigation.indexes",
  "navigation.instant",
  "navigation.instant.prefetch",
  "navigation.path",
  "navigation.tabs",
  "navigation.sections",
  "navigation.top",
  "navigation.tracking",
  "search.highlight",
  "navigation.prune",
]

[[project.theme.palette]]
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Dark mode"

[[project.theme.palette]]
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Light mode"

[project.theme.icon]
repo = "fontawesome/brands/github"
