[project]
site_name = "page"
repo_url = "https://github.com/josephbarbierdarnal/page"
site_url = "https://josephbarbierdarnal.github.io/page/"
site_description = "PDF/A and PDF/UA validation engine"
site_author = "Joseph Barbier"
extra_css = ["stylesheets/style.css"]
nav = [
  { "Home" = "index.md" },
  { "Installation" = "installation.md" },
  { "Usage" = [
    { "CLI" = "api/cli.md" },
    { "Rust" = "api/rust.md" },
    { "Python" = "api/python.md" },
  ] },
  { "Rules" = [
    { "PDF/A-1" = "rules/pdfa-1-rules.md" },
    { "PDF/A-2 and PDF/A-3" = "rules/pdfa-2-3-rules.md" },
    { "PDF/UA-1" = "rules/pdfua-1-rules.md" },
  ] },
  { "About" = [
    { "FAQ" = "about/faq.md" },
    { "PDF Format" = "about/pdf-format.md" },
  ] },
]

[project.theme]
logo = "images/logo-on-light.svg"
language = "en"
custom_dir = "docs/overrides"
features = [
  "announce.dismiss",
  "content.code.annotate",
  "content.code.copy",
  "content.footnote.tooltips",
  "content.tooltips",
  "navigation.footer",
  "navigation.indexes",
  "navigation.instant",
  "navigation.instant.prefetch",
  "navigation.path",
  "navigation.tabs",
  "navigation.sections",
  "navigation.top",
  "navigation.tracking",
  "search.highlight",
  "navigation.prune",
]

[[project.theme.palette]]
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Dark mode"

[[project.theme.palette]]
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Light mode"

[project.theme.icon]
repo = "fontawesome/brands/github"
