//! The predefined CMap collection bundled by veraPDF 1.28.2.
//!
//! These byte-exact resources are the data its font model resolves for a
//! named Type0 `/Encoding`. Keeping the lookup private avoids exposing Adobe
//! CMap details as part of page's public API.

pub(crate) fn get(name: &[u8]) -> Option<&'static [u8]> {
    macro_rules! cmap {
        ($name:literal) => {
            include_bytes!(concat!("predefined_cmaps/", $name)).as_slice()
        };
    }

    Some(match name {
        b"83pv-RKSJ-H" => cmap!("83pv-RKSJ-H"),
        b"90ms-RKSJ-H" => cmap!("90ms-RKSJ-H"),
        b"90ms-RKSJ-V" => cmap!("90ms-RKSJ-V"),
        b"90msp-RKSJ-H" => cmap!("90msp-RKSJ-H"),
        b"90msp-RKSJ-V" => cmap!("90msp-RKSJ-V"),
        b"90pv-RKSJ-H" => cmap!("90pv-RKSJ-H"),
        b"90pv-RKSJ-V" => cmap!("90pv-RKSJ-V"),
        b"Add-RKSJ-H" => cmap!("Add-RKSJ-H"),
        b"Add-RKSJ-V" => cmap!("Add-RKSJ-V"),
        b"Adobe-CNS1-0" => cmap!("Adobe-CNS1-0"),
        b"Adobe-CNS1-1" => cmap!("Adobe-CNS1-1"),
        b"Adobe-CNS1-2" => cmap!("Adobe-CNS1-2"),
        b"Adobe-CNS1-3" => cmap!("Adobe-CNS1-3"),
        b"Adobe-CNS1-4" => cmap!("Adobe-CNS1-4"),
        b"Adobe-CNS1-5" => cmap!("Adobe-CNS1-5"),
        b"Adobe-CNS1-6" => cmap!("Adobe-CNS1-6"),
        b"Adobe-CNS1-7" => cmap!("Adobe-CNS1-7"),
        b"Adobe-CNS1-UCS2" => cmap!("Adobe-CNS1-UCS2"),
        b"Adobe-GB1-0" => cmap!("Adobe-GB1-0"),
        b"Adobe-GB1-1" => cmap!("Adobe-GB1-1"),
        b"Adobe-GB1-2" => cmap!("Adobe-GB1-2"),
        b"Adobe-GB1-3" => cmap!("Adobe-GB1-3"),
        b"Adobe-GB1-4" => cmap!("Adobe-GB1-4"),
        b"Adobe-GB1-5" => cmap!("Adobe-GB1-5"),
        b"Adobe-GB1-6" => cmap!("Adobe-GB1-6"),
        b"Adobe-GB1-UCS2" => cmap!("Adobe-GB1-UCS2"),
        b"Adobe-Japan1-0" => cmap!("Adobe-Japan1-0"),
        b"Adobe-Japan1-1" => cmap!("Adobe-Japan1-1"),
        b"Adobe-Japan1-2" => cmap!("Adobe-Japan1-2"),
        b"Adobe-Japan1-3" => cmap!("Adobe-Japan1-3"),
        b"Adobe-Japan1-4" => cmap!("Adobe-Japan1-4"),
        b"Adobe-Japan1-5" => cmap!("Adobe-Japan1-5"),
        b"Adobe-Japan1-6" => cmap!("Adobe-Japan1-6"),
        b"Adobe-Japan1-7" => cmap!("Adobe-Japan1-7"),
        b"Adobe-Japan1-UCS2" => cmap!("Adobe-Japan1-UCS2"),
        b"Adobe-Japan2-0" => cmap!("Adobe-Japan2-0"),
        b"Adobe-KR-0" => cmap!("Adobe-KR-0"),
        b"Adobe-KR-1" => cmap!("Adobe-KR-1"),
        b"Adobe-KR-2" => cmap!("Adobe-KR-2"),
        b"Adobe-KR-3" => cmap!("Adobe-KR-3"),
        b"Adobe-KR-4" => cmap!("Adobe-KR-4"),
        b"Adobe-KR-5" => cmap!("Adobe-KR-5"),
        b"Adobe-KR-6" => cmap!("Adobe-KR-6"),
        b"Adobe-KR-7" => cmap!("Adobe-KR-7"),
        b"Adobe-KR-8" => cmap!("Adobe-KR-8"),
        b"Adobe-KR-9" => cmap!("Adobe-KR-9"),
        b"Adobe-KR-UCS2" => cmap!("Adobe-KR-UCS2"),
        b"Adobe-Korea1-0" => cmap!("Adobe-Korea1-0"),
        b"Adobe-Korea1-1" => cmap!("Adobe-Korea1-1"),
        b"Adobe-Korea1-2" => cmap!("Adobe-Korea1-2"),
        b"Adobe-Korea1-UCS2" => cmap!("Adobe-Korea1-UCS2"),
        b"B5pc-H" => cmap!("B5pc-H"),
        b"B5pc-V" => cmap!("B5pc-V"),
        b"CNS-EUC-H" => cmap!("CNS-EUC-H"),
        b"CNS-EUC-V" => cmap!("CNS-EUC-V"),
        b"ETen-B5-H" => cmap!("ETen-B5-H"),
        b"ETen-B5-V" => cmap!("ETen-B5-V"),
        b"ETenms-B5-H" => cmap!("ETenms-B5-H"),
        b"ETenms-B5-V" => cmap!("ETenms-B5-V"),
        b"EUC-H" => cmap!("EUC-H"),
        b"EUC-V" => cmap!("EUC-V"),
        b"Ext-RKSJ-H" => cmap!("Ext-RKSJ-H"),
        b"Ext-RKSJ-V" => cmap!("Ext-RKSJ-V"),
        b"GB-EUC-H" => cmap!("GB-EUC-H"),
        b"GB-EUC-V" => cmap!("GB-EUC-V"),
        b"GB-H" => cmap!("GB-H"),
        b"GB-V" => cmap!("GB-V"),
        b"GBK-EUC-H" => cmap!("GBK-EUC-H"),
        b"GBK-EUC-V" => cmap!("GBK-EUC-V"),
        b"GBK2K-H" => cmap!("GBK2K-H"),
        b"GBK2K-V" => cmap!("GBK2K-V"),
        b"GBKp-EUC-H" => cmap!("GBKp-EUC-H"),
        b"GBKp-EUC-V" => cmap!("GBKp-EUC-V"),
        b"GBT-EUC-H" => cmap!("GBT-EUC-H"),
        b"GBT-EUC-V" => cmap!("GBT-EUC-V"),
        b"GBT-H" => cmap!("GBT-H"),
        b"GBT-V" => cmap!("GBT-V"),
        b"GBTpc-EUC-H" => cmap!("GBTpc-EUC-H"),
        b"GBTpc-EUC-V" => cmap!("GBTpc-EUC-V"),
        b"GBpc-EUC-H" => cmap!("GBpc-EUC-H"),
        b"GBpc-EUC-V" => cmap!("GBpc-EUC-V"),
        b"H" => cmap!("H"),
        b"HKscs-B5-H" => cmap!("HKscs-B5-H"),
        b"HKscs-B5-V" => cmap!("HKscs-B5-V"),
        b"Identity-H" => cmap!("Identity-H"),
        b"Identity-V" => cmap!("Identity-V"),
        b"KSC-EUC-H" => cmap!("KSC-EUC-H"),
        b"KSC-EUC-V" => cmap!("KSC-EUC-V"),
        b"KSCms-UHC-H" => cmap!("KSCms-UHC-H"),
        b"KSCms-UHC-HW-H" => cmap!("KSCms-UHC-HW-H"),
        b"KSCms-UHC-HW-V" => cmap!("KSCms-UHC-HW-V"),
        b"KSCms-UHC-V" => cmap!("KSCms-UHC-V"),
        b"KSCpc-EUC-H" => cmap!("KSCpc-EUC-H"),
        b"KSCpc-EUC-V" => cmap!("KSCpc-EUC-V"),
        b"UniAKR-UTF16-H" => cmap!("UniAKR-UTF16-H"),
        b"UniCNS-UCS2-H" => cmap!("UniCNS-UCS2-H"),
        b"UniCNS-UCS2-V" => cmap!("UniCNS-UCS2-V"),
        b"UniCNS-UTF16-H" => cmap!("UniCNS-UTF16-H"),
        b"UniCNS-UTF16-V" => cmap!("UniCNS-UTF16-V"),
        b"UniGB-UCS2-H" => cmap!("UniGB-UCS2-H"),
        b"UniGB-UCS2-V" => cmap!("UniGB-UCS2-V"),
        b"UniGB-UTF16-H" => cmap!("UniGB-UTF16-H"),
        b"UniGB-UTF16-V" => cmap!("UniGB-UTF16-V"),
        b"UniGB-UTF32-H" => cmap!("UniGB-UTF32-H"),
        b"UniGB-UTF32-V" => cmap!("UniGB-UTF32-V"),
        b"UniGB-UTF8-H" => cmap!("UniGB-UTF8-H"),
        b"UniGB-UTF8-V" => cmap!("UniGB-UTF8-V"),
        b"UniJIS-UCS2-H" => cmap!("UniJIS-UCS2-H"),
        b"UniJIS-UCS2-HW-H" => cmap!("UniJIS-UCS2-HW-H"),
        b"UniJIS-UCS2-HW-V" => cmap!("UniJIS-UCS2-HW-V"),
        b"UniJIS-UCS2-V" => cmap!("UniJIS-UCS2-V"),
        b"UniJIS-UTF16-H" => cmap!("UniJIS-UTF16-H"),
        b"UniJIS-UTF16-V" => cmap!("UniJIS-UTF16-V"),
        b"UniKS-UCS2-H" => cmap!("UniKS-UCS2-H"),
        b"UniKS-UCS2-V" => cmap!("UniKS-UCS2-V"),
        b"UniKS-UTF16-H" => cmap!("UniKS-UTF16-H"),
        b"UniKS-UTF16-V" => cmap!("UniKS-UTF16-V"),
        b"V" => cmap!("V"),
        _ => return None,
    })
}
