[package]
name = "page_validation"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "PDF/A and PDF/UA validation."
documentation = "https://josephbarbierdarnal.github.io/page/"
readme = "../../README.md"
homepage = "https://josephbarbierdarnal.github.io/page/"
repository = "https://github.com/josephbarbierdarnal/page"
license = "MIT AND BSD-3-Clause AND Apache-2.0"
keywords = ["PDF", "profile", "validation", "verapdf"]
exclude = ["/tests/"]

[dependencies]
chrono = "0.4"
lopdf = "0.44"
roxmltree = "0.21"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sxd-xpath = "0.4.2"
thiserror = "2"
ttf-parser = "0.25.1"
unicode-properties = "0.1"

[dev-dependencies]
sha2 = "0.11"

[target.'cfg(not(all(target_arch = "wasm32", target_os = "unknown")))'.dependencies]
wait-timeout = "0.2"

[lints]
workspace = true
