name: Wasm | Typing

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  typescript:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.4.2
      - uses: dtolnay/rust-toolchain@stable
      - uses: jetli/wasm-pack-action@v0.4.0
        with:
          version: latest
      - run: bun install --frozen-lockfile
      - run: bun run --cwd crates/page_wasm build
      - run: bun run --cwd crates/page_wasm typecheck
